import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// import theme provider
import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
// import TrpcProvider from "@/components/trpcProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          {/* <TrpcProvider> */}
            <Navbar />
            {children}
            <Footer />
          {/* </TrpcProvider> */}
        </ThemeProvider>
        {/* {children} */}
      </body>
    </html>
  );
}
